title: "Shop"
menu:
  0:
    shop: true
    icon:
      material: IRON_ORE
      name: "Minerals"
    items:
      - "GLOWSTONE"
      - "NETHER_QUARTZ_ORE"
      - "#lapis_ores"
      - "#coal_ores"
      - "#iron_ores"
      - "#emerald_ores"
      - "#gold_ores"
      - "#diamond_ores"
      - "#redstone_ores"
      - "#copper_ores"
      - "RAW_IRON"
      - "RAW_COPPER"
      - "RAW_GOLD"
      - "IRON_INGOT"
      - "COPPER_INGOT"
      - "GOLD_INGOT"
      - "REDSTONE"
      - "COAL"
      - "DIAMOND"
  1:
    shop: true
    icon:
      material: BREAD
      name: "Food"
    items:
      - "APPLE"
      - "MUSHROOM_STEW"
      - "BREAD"
      - "PORKCHOP"
      - "COOKED_PORKCHOP"
      - "COD"
      - "SALMON"
      - "COOKED_COD"
      - "COOKED_SALMON"
      - "COOKIE"
      - MELON_SLICE
      - DRIED_KELP
      - BEEF
      - COOKED_BEEF
      - CHICKEN
      - COOKED_CHICKEN
      - "CARROT"
      - "POTATO"
      - BAKED_POTATO
      - "PUMPKIN_PIE"
      - RABBIT
      - COOKED_RABBIT
      - RABBIT_STEW
      - MUTTON
      - COOKED_MUTTON
      - BEETROOT
      - BEETROOT_SOUP
      - SWEET_BERRIES
  2:
    shop: false
  3:
    shop: false
  4:
    shop: false
  5:
    shop: false
  6:
    shop: false
  7:
    shop: false
  8:
    shop: false
  9:
    shop: false
  10:
    shop: false
  11:
    shop: false
  12:
    shop: false
  13:
    shop: false
  14:
    shop: false
  15:
    shop: false
  16:
    shop: false
  17:
    shop: false
  18:
    shop: false
  19:
    shop: false
  20:
    shop: false
  21:
    shop: false
  22:
    shop: false
    # Slot 22 will be on slot 23 due to reasons
  23:
    shop: false
  24:
    shop: false
  25:
    shop: false
